### ISSUE TITLE
Don't run in  Windows

### ISSUE THREAD

**Issue by DinhCongTac221** [prabhakar267/ocr-convert-image-to-text#18] opened 2018-07-29 15:44 UTC
Hello,
I Tried so hard to run your program. But it don't work. 
My computer has installed Tesseract-orc ( Window)
Please help me, How to run on windows.
thanks
![image](https://user-images.githubusercontent.com/27664184/43368045-d40ce432-9380-11e8-88c6-20528b3120d7.png)

**Comment by avsaditya** [comment] 2018-09-10 07:40
Hi, 

I think the problem is with your environment.
Add tesseract/bin to your path and create an environment variable with the name TESSDATA_PREFIX and set it to the path of your trained data.
Before doing this, uninstall tesseract from your site-packages and after the process install again.

Please do this and let me know in case of any issues.

Thanks and Regards
Aditya

**Comment by prabhakar267** [comment] 2018-09-10 09:22
@buidoi8x does it solve your issue?

**Comment by prabhakar267** [comment] 2018-09-10 11:51
Fixed by 3ec4092e933686d92ca31f0ed5e073c059258a34

**Closed as completed by prabhakar267** 2018-09-10 11:51 UTC

**Comment by DinhCongTac221** [comment] 2018-09-10 13:24
Thank you. It works with file example.
But I don't know why, It doesnot correct with my image text
![image](https://user-images.githubusercontent.com/27664184/45300045-842a6600-b537-11e8-9dbb-ad810def2769.png)

**Comment by avsaditya** [comment] 2018-09-11 06:14
Hi,

Can you please send/attach your image files?
I think the problem might be with the low resolution of the images.
You could enhance the DPI level before doing OCR.

Thanks and Regards
Aditya

**Comment by DinhCongTac221** [comment] 2018-09-11 06:43
sure. the problem might be with the low resolution of the images.
![1](https://user-images.githubusercontent.com/27664184/45342516-6c4ef280-b5c8-11e8-86d0-5635ae199d11.jpg)
![2](https://user-images.githubusercontent.com/27664184/45342519-6c4ef280-b5c8-11e8-86be-8336de19f25d.jpg)

**Comment by avsaditya** [comment] 2018-09-12 17:04
I tried enhancing the dpi and processed the image a bit but I think they are of too low resolution.
OCR doesn't work correctly.
Sorry.
